name: pinelogger
description: An alternative logger for Dart.
version: 1.1.0
homepage: https://github.com/bleonard252/pinelogger

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  rxdart: ^0.27.5

dev_dependencies: {}