name: pinelogger_flutter
description: Pinelogger extensions for Flutter.
version: 1.0.0
homepage: https://github.com/bleonard252/pinelogger/tree/main/pinelogger_flutter

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  pinelogger: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: {}